# AppVeyor CI build file

# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

# version format
version: 1.0.{build}
image: Visual Studio 2019

shallow_clone: true

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# to run your custom scripts instead of automatic MSBuild
build_script:
  - cmd: build.bat Package

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

# to disable automatic tests 
test: false

# skip building commits that add tags (such as release tag)
skip_tags: true

skip_commits:
  author: Shimrockx
  files:
    - docs/*
    - README.md
    - LICENSE

#---------------------------------#
#       artifacts configuration   #
#---------------------------------#

artifacts:
  - path: '**\APM Meter.exe'